version: '3'

services:
  nats-docker:
    image: nats:latest
    container_name: nats-srv
    expose:
      - "4222"
      - "6222"
      - "8222"
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    command: ["--js", "-V"]
  node-18-dev-docker:
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: node-18-dev
    expose:
      - '3000'
      - '3001'
    ports:
      - '3000:3000'
      - '3001:3001'
    command: tail -f

